### PR TITLE
Allow `Node.suffixIds` to update multiple attributes. This fixes #52.

### LINKED ISSUE #52: `Node.suffixIds` to update references also
It would be awesome if `Node.suffixIds()` could also update id references.

For example:

```scala
val template = html"""
<label for="tags">Tags</label>
<input id="tags" type="text" aria-describedby="tags-help"/>
<p id="tags-help"></p>
"""

assert(template.suffixIds("1").toHtml === """
<label for="tags1">Tags</label>
<input id="tags1" type="text" aria-describedby="tags-help1"/>
<p id="tags-help1"></p>
""")
```

Note that the `for` and `aria-describedby` attributes are also updated. Maybe there are more 'standard' attributes that should be updated like this.

### PR DESCRIPTION
**Pull request by erikvanoosten**

### CODE REVIEW

**Comment by erikvanoosten** [comment]
Sorry for the multiple commits. I could not run the tests locally, so I had to rely on Travis.

**Comment by tindzk** [comment]
Thanks for tackling the issue! It looks great. Could you squash the commits into one?

**Comment by erikvanoosten** [comment]
Eh, I'll try :)

**Comment by erikvanoosten** [comment]
Superseded by #53.

**Comment by erikvanoosten** [comment]
Just FYI:
I just went through https://w3c.github.io/html/fullindex.html#attributes-table and also found the following attributes: `form`, `headers`.
In addition, I noticed that `for` (on an `output`) and `headers` accept space separated lists of ids.

**Comment by erikvanoosten** [comment]
Just FYI:
I just went through https://w3c.github.io/html/fullindex.html#attributes-table and also found the following attributes: form, headers.
In addition, I noticed that for (on an output) and headers accept space separated lists of ids.

**Comment by tindzk** [comment]
Thanks, I added `form` and `headers`. We can further improve on the logic in the future.

**Pull request closed without merging**
