### PR TITLE
Allow spaces before and after equal sign in attribute definition

### PR DESCRIPTION
**Pull request by lavrov**

### CODE REVIEW

**Comment by tindzk** [comment]
Thanks for pull request! The CI checks are failing, but this appears to be unrelated to your changes. I will look more into it.

**Comment by tindzk** [comment]
I have just merged a tiny fix to `master`. Would you mind rebasing your pull request?

**Comment by lavrov** [comment]
Rebased

**Comment by tindzk** [comment]
Great, thanks!

**Pull request merged**
